app = "zordcoder"

[machines]
  auto_stop = true
  auto_start = true

[http_service]
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[deploy]
  strategy = "immediate"

[[services]]
  internal_port = 8080
  processes = ["app"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "60s"
