[theme]
base = "dark"
primaryColor = "#10B981"
backgroundColor = "#000000"
secondaryBackgroundColor = "#0A0A0A"
textColor = "#FFFFFF"
font = "sans serif"

[server]
port = 8501
headless = true

[browser]
gatherUsageStats = false
